# Generated by Django 4.2.18 on 2025-02-03 11:46

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('developer', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('release_date', models.DateField(default='2021-01-01')),
                ('game_version', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('playtime', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('game_info', models.TextField(default='')),
                ('awards_won', models.TextField(default='')),
                ('technical_refresh_rate', models.IntegerField(default=60)),
                ('technical_hdr', models.BooleanField(default=False)),
                ('technical_storagesize', models.IntegerField(default=0)),
                ('technical_online_play', models.BooleanField(default=False)),
                ('technical_online_players', models.IntegerField(default=0)),
                ('technical_online_crossplay', models.BooleanField(default=False)),
                ('technical_monthly_concurrent_players', models.IntegerField(default=0)),
                ('platinum_trophies', models.BooleanField(default=False)),
                ('trophy_ammount', models.IntegerField(default=0)),
                ('patch_notes', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('excerpt', models.TextField(blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
