# Generated by Django 4.2.18 on 2025-02-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='awards_won',
            field=models.TextField(default='No Awards Have Been Posted Here Yet..'),
        ),
        migrations.AlterField(
            model_name='post',
            name='playtime',
            field=models.IntegerField(default=0),
        ),
    ]
