# Generated by Django 4.2.18 on 2025-02-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_post_awards_won_alter_post_playtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='game_platform_ps4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='game_platform_ps5',
            field=models.BooleanField(default=False),
        ),
    ]
