# Generated by Django 4.2.18 on 2025-02-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_post_age_rating_post_game_platform_ps4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='game_platform_ps4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='game_platform_ps5',
        ),
        migrations.AddField(
            model_name='post',
            name='game_platform',
            field=models.TextField(default='PS_ PS_'),
        ),
    ]
