# Generated by Django 4.2.18 on 2025-02-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.CharField(blank=True, default='Unknown', max_length=200),
        ),
    ]
