# Generated by Django 4.2.18 on 2025-02-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_post_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='trophy_ammount',
            new_name='trophy_amount',
        ),
    ]
