# Generated by Django 4.2.18 on 2025-02-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_trophy_ammount_post_trophy_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='technical_online_crossplay',
            new_name='technical_online_console_crossplay',
        ),
        migrations.AddField(
            model_name='post',
            name='technical_online_pc_crossplay',
            field=models.BooleanField(default=False),
        ),
    ]
