# Generated by Django 4.2.18 on 2025-02-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_technical_online_crossplay_post_technical_online_console_crossplay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='patch_notes',
        ),
        migrations.AddField(
            model_name='post',
            name='patch_notes_url',
            field=models.TextField(default='https://store.playstation.com/en-gb/pages/latest'),
        ),
    ]
