# Generated by Django 4.2.18 on 2025-02-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_post_patch_notes_post_patch_notes_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='patch_notes_url',
            field=models.URLField(default='https://store.playstation.com/en-gb/pages/latest'),
        ),
    ]
