# Generated by Django 4.2.18 on 2025-02-03 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_post_patch_notes_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='game_version',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='comment',
            name='glitched_trophies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='glitched_trophies_list',
            field=models.TextField(default='No Glitched Trophies Have Been Posted Here Yet..'),
        ),
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='platform',
            field=models.TextField(default='PS_'),
        ),
        migrations.AddField(
            model_name='comment',
            name='platinum_achieveved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='platinum_stability',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='comment',
            name='playtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
