# Generated by Django 4.2.18 on 2025-02-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_comment_game_version_comment_glitched_trophies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='platform',
            field=models.CharField(choices=[('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5')], default='PS4', max_length=3),
        ),
    ]
