# Generated by Django 4.2.18 on 2025-02-05 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_comment_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trophy_achieved_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='trophy_duration_to_plat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='trophy_plat_difficulty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='post',
            name='trophy_plat_glitchiness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
