# Generated by Django 4.2.18 on 2025-02-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_post_trophy_achieved_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='technical_ray_tracing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='technical_subtitles',
            field=models.BooleanField(default=False),
        ),
    ]
