# Generated by Django 4.2.18 on 2025-02-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_post_technical_ray_tracing_post_technical_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='technical_vrr',
            field=models.BooleanField(default=False),
        ),
    ]
