# Generated by Django 4.2.18 on 2025-02-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_platinum_achieveved_comment_platinum_achieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='heading',
            field=models.CharField(default='Comment', max_length=200),
        ),
    ]
