# Generated by Django 4.2.18 on 2025-02-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_comment_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='heading',
            new_name='title',
        ),
    ]
