# Generated by Django 4.2.18 on 2025-02-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='awards_shown',
            field=models.BooleanField(default=False),
        ),
    ]
