# Generated by Django 4.2.18 on 2025-02-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_post_awards_shown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='awards_won',
            field=models.TextField(default='Award Name "Best Game of the Year", Awarding Organization (e.g., "The Game Awards") Year of Award Category (e.g., "Best Action Game")'),
        ),
    ]
