# Generated by Django 4.2.18 on 2025-02-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_post_awards_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='post',
            name='awards_won',
            field=models.TextField(default='Award Name - "Best Game of the Year"\nAwarding Organization - "The Game Awards"\nYear of Award - "2025"\nCategory - "Best Action Game'),
        ),
    ]
