# Generated by Django 4.2.18 on 2025-02-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_comment_glitched_trophies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='glitched_trophies',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
