# Generated by Django 4.2.18 on 2025-02-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollaborateRequest',
            new_name='SupportRequest',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
