# Generated by Django 4.2.18 on 2025-02-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_rename_collaboraterequest_supportrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='issue_type',
            field=models.CharField(choices=[('technical', 'Technical Issue'), ('billing', 'Billing Issue'), ('general', 'General Inquiry')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
