# Generated by Django 4.2.18 on 2025-02-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportrequest_issue_type_alter_supportrequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='issue_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Issue'), ('billing', 'Billing Issue')], default='general', max_length=50),
        ),
    ]
