# Generated by Django 4.2.18 on 2025-02-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='games_purchased',
            field=models.TextField(default=''),
        ),
    ]
