# Generated by Django 4.2.18 on 2025-02-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0006_alter_game_games_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Grand_Theft_Auto_VI',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='games_purchased',
            field=models.TextField(default='Testing 123\nTesting 456'),
        ),
    ]
