# Generated by Django 4.2.18 on 2025-02-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0007_game_grand_theft_auto_vi_alter_game_games_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Astro_Bot',
            field=models.BooleanField(default=False),
        ),
    ]
