# Generated by Django 4.2.18 on 2025-02-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_comment_title'),
        ('account_profile', '0009_remove_game_astro_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='purchased_games',
            field=models.ManyToManyField(blank=True, related_name='purchased_games', to='store.post'),
        ),
    ]
