# Generated by Django 4.2.18 on 2025-02-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_post_excerpt_alter_post_awards_won'),
        ('account_profile', '0011_remove_profile_content_remove_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='games_purchased',
        ),
        migrations.AlterField(
            model_name='profile',
            name='purchased_games',
            field=models.ManyToManyField(blank=True, default='Astro Bot', related_name='purchased_games', to='store.post'),
        ),
    ]
