# Generated by Django 4.2.18 on 2025-02-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_post_excerpt_alter_post_awards_won'),
        ('account_profile', '0012_remove_game_games_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='purchased_games',
            field=models.ManyToManyField(blank=True, related_name='purchased_games', to='store.post'),
        ),
    ]
