# Generated by Django 4.2.18 on 2025-02-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_post_excerpt_alter_post_awards_won'),
        ('account_profile', '0014_alter_profile_purchased_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='games_purchased',
            field=models.ManyToManyField(blank=True, default='Astro Bot', related_name='games_purchased', to='store.post'),
        ),
    ]
