# Generated by Django 4.2.18 on 2025-02-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0015_game_games_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='games_purchased',
        ),
        migrations.AddField(
            model_name='game',
            name='games_purchased',
            field=models.TextField(default=''),
        ),
    ]
