# Generated by Django 4.2.18 on 2025-02-10 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_comment_glitched_trophies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_profile', '0016_remove_game_games_purchased_game_games_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='purchased_games',
            field=models.ManyToManyField(blank=True, related_name='purchased_games', to='store.post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
